### ISSUE TITLE
Enigma2 YT and Quality Select Not Work

### ISSUE THREAD

**Issue by thawtes** [livecli/livecli#19]
hi,

YT links not work
`#SERVICE 4097:0:1:0:0:0:0:0:0:0:http%3a//127.0.0.1%3a53473/play/?url=https%3a//www.youtube.com/watch?v=_tqiBzkdsqE:YT TEST
#DESCRIPTION YT TEST`

and Quality Select not work or how to ? my examples
`4097:0:1:0:0:0:0:0:0:0:http%3a//127.0.0.1%3a53473/play/?url=tr.euronews.com/live,360p
or
http%3a//127.0.0.1%3a53473/play/?url=tr.euronews.com/live?default-stream=360p`

**maybe it actually works but not playing ?**

var/log/livecli-server.log
`[cli][info] livecli is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.5-mips-with-glibc2.0
[cli][debug] Python:     2.7.13
[cli][debug] Livecli:    3.6.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Starting server: 0.0.0.0 on port 53473
[ID-633728][livecli-server][info] User-Agent: Enigma2 HbbTV/1.1.1 (+PVR+RTSP+DL;openATV;;;)
[ID-633728][livecli-server][info] Client: ('127.0.0.1', 35796)
[ID-633728][livecli-server][info] Address: localhost.localdomain
[ID-633728][plugin.youtube][debug] get_video_info - 1: Found data
[ID-633728][plugin.youtube][debug] MuxedStream: v 137 a 251 = 1080p
127.0.0.1 - - [02/Apr/2018 04:48:51] "GET /play/?url=https://www.youtube.com/watch?v=_tqiBzkdsqE HTTP/1.1" 404 -`

my device is vu+duo2  (livecli 3.6.2)

thanks

**Comment by back-to** [comment]
Hello,

the quality option did not work well,

I changed it and you will have to **update** your livecli version to **3.7.0**

`https://raw.githubusercontent.com/livecli/ipk/master/build/python-livecli_3.7.0_all.ipk`

---

Here is an **example** of how to use the parameter.

**From the begin to the end.**

the base use is

`http://127.0.0.1:53473/play/?`

after this url, you will have to add all parameter for every new parameter you will need an `&`

most of the parameter from https://livecli.github.io/cli.html#general-options should work
just remove the `--`

---

`http://127.0.0.1:53473/play/?url=http://example.com`

with quality `q=360p` you will add `&q=360p`

`http://127.0.0.1:53473/play/?url=http://example.com&q=360p`

`q quality stream default-stream` everything should work as quality option

---

You should use https://www.urlencoder.org/ for the parameter with **symboles** such as `?` `&`

for

`url=https://www.youtube.com/watch?v=_tqiBzkdsqE`

it will be

`url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_tqiBzkdsqE`

---

with quality

`http://127.0.0.1:53473/play/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_tqiBzkdsqE&q=360p`

because you are using the E2 userbouquet

No `:` is allowed in an url, use `%3a`

`http%3a//127.0.0.1%3a53473/play/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_tqiBzkdsqE&q=360p`

---

Euronews for E2

`http%3a//127.0.0.1%3a53473/play/?url=http%3a//tr.euronews.com/live&q=360p`

---

**some youtube** streams use MuxedStream / **ffmpeg for +720p**

but livecli can currently only change the video quality not the audio quality,
so the **bitrate** for the audio quality **might be to high** for lower streams.

---

you might see an error at the end of a stream,
you can **ignore them** if your stream ends normally.

such as

```
[ID-659035][livecli-server][debug] Valid quality: 360p
127.0.0.1 - - "GET /play/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_tqiBzkdsqE&q=360p HTTP/1.1" 200 -
[ID-659035][livecli-server][debug] Pre-buffering 4096 bytes
[ID-659035][livecli-server][error] No Data!
[ID-659035][livecli-server][info] Stream ended
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45298)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 407, in handle_one_request
    self.wfile.flush() #actually send the response if not already done.
ValueError: I/O operation on closed file.
----------------------------------------
```
